services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: post-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: post_service_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: post_service_phpmyadmin
    environment:
      PMA_HOST: post-db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: user_password
    ports:
      - "8085:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
