services:
  # container_name: "XDPMTMHPL"
  mysql:
    image: "mysql:lts"
    container_name: "user-service-mysql"
    environment:
      - "MYSQL_DATABASE=user_service"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=user_service"
      - "MYSQL_PASSWORD=root"
    ports:
      - "3306:3306"
    networks:
      - "database-network"

  phpmyadmin:
    image: "phpmyadmin:latest"
    container_name: "phpmyadmin"
    environment:
      - "PMA_ARBITRARY=1"
    ports:
      - "80:80"
    depends_on:
      - "mysql"
    networks:
      - "database-network"

networks:
  database-network:
    driver: "bridge"
