spring.application.name=friend-service

spring.datasource.url=jdbc:mysql://friend-db:3306/friend_service
spring.datasource.username=friend_service
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
