spring.application.name=notification_service

server.port=8085

# spring.datasource.url=jdbc:postgresql://notification_db:5432/notification_service
spring.datasource.url=jdbc:postgresql://127.0.0.1:3311/notification_service
spring.datasource.username=notification_user
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
